#!/bin/bash
set -e

CURRENTDIR=$(pwd)
HOSTNAME="sensornode"

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Update all packages
git submodule update --init --recursive

# Change the hostname
sed -i "s/raspberrypi/${HOSTNAME}/g" /etc/hosts
echo $HOSTNAME > /etc/hostname
echo $HOSTNAME > /boot/hostnames
echo "Hostname changed to $HOSTNAME"

cd $CURRENTDIR

ln -s $CURRENTDIR/START /etc/init.d/willy
update-rc.d willy enable

reboot now
