#!/bin/bash
set -e

CURRENTDIR=$(pwd)

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

git submodule update --init --recursive

# Install Apriltags
cd $CURRENTDIR/components/openmv_apriltag
exec ./INSTALL

# Install Sonar
cd $CURRENTDIR/components/sonar
exec ./INSTALL

# Install Pose Tracking
cd $CURRENTDIR/components/pose_tracking
exec ./INSTALL

cd $CURRENTDIR
