#!/bin/bash
set -e

CURRENTDIR=$(pwd)

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

git submodule update --init --recursive

# Install motor controller
cd $CURRENTDIR/components/motor_controller
exec ./INSTALL

# Install keyboard and joystick
cd $CURRENTDIR/components/keyboard
exec ./INSTALL

cd $CURRENTDIR
