#!/bin/bash
### BEGIN INIT INFO
# Provides: willy
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description:  Enable willy processes
### END INIT INFO

WOKRING_DIR="/opt/willy"
cd $WOKRING_DIR

case "$1" in
start)
  cd $WOKRING_DIR/openmv
  exec ./START start &>/dev/null &
  cd $WOKRING_DIR/sonar
  exec ./START start &>/dev/null &
  cd $WOKRING_DIR/pose_tracking/mpu6050_serial_to_imu
  exec ./START start &>/dev/null &
  ;;
stop)
  cd $WOKRING_DIR/openmv
  exec ./START stop
  cd $WOKRING_DIR/sonar
  exec ./START stop
  cd $WOKRING_DIR/pose_tracking/mpu6050_serial_to_imu
  exec ./START stop
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
